### ISSUE TITLE
IndexError: list index out of range -  on building html

### ISSUE THREAD

**Issue by julyate** [tk0miya/sphinxcontrib-apiblueprint#1]
Added an .apib file to my sphinx docs, got this error when building:

`File "/venv/lib/python2.7/site-packages/sphinxcontrib/apiblueprint/addnodes.py", line 103, in restruct
    body = get_children(self, Body)[0]
IndexError: list index out of range`

Let me know if I can supply any additional info

**Comment by julyate** [comment]
Installed latest version from github (previous installation via pip):

`File "venv/lib/python2.7/site-packages/sphinxcontrib/apiblueprint/addnodes.py", line 48, in restruct
    body = get_children(self, Body)[0]
IndexError: list index out of range`

**Comment by tk0miya** [comment]
Sorry for late response. I will restart developing at beginning of Aug.

Could you show me the your input .apib file and full stacktrace?

**Comment by julyate** [comment]
Thanks! The .apib file is attached as source.txt, and the full stack trace is in error.txt

[error.txt](https://github.com/tk0miya/sphinxcontrib-apiblueprint/files/390342/error.txt)
[source.txt](https://github.com/tk0miya/sphinxcontrib-apiblueprint/files/390347/source.txt)

**Comment by tk0miya** [comment]
Thank you for additional info.
It would be fixed at 43bbd505fdf3502e94451635bca9691f33859f4c.

**Comment by julyate** [comment]
Thanks, working now!
